# Generated by Django 3.2.16 on 2022-11-21 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
